### ISSUE TITLE
Tapping buttons on Galaxy S7 tends to select text

### ISSUE THREAD

**Issue by NateEag** [jperryhouts/Dual-N-Back#2]
In Firefox on my Galaxy S7, when I tap the Eye and Sound buttons while playing, I fairly often activate text selection.

Fixing this might be as easy as setting `user-select: none` in the CSS for those buttons. I'm on my S7 right now or I might just try it myself.

**Comment by jperryhouts** [comment]
Thanks for the heads up -- I'll  look into this over the weekend.

**Comment by NateEag** [comment]
Thanks very much!

And no pressure - I'd be happy to take a look at it myself if that would help. I remember you saying you weren't using this much last time I filed an issue.

**Comment by jperryhouts** [comment]
Thanks, but that was an easy fix (d20bdf3). Those changes are live on the website. Let me know if that didn't solve it.

**Comment by NateEag** [comment]
Works like a charm now. 

Thanks so much!
