### ISSUE TITLE
Mobile app (Android/iOS) doesn't work 

### ISSUE THREAD

**Issue by tehniksit** [jperryhouts/Dual-N-Back#7]
Web browser based mobile app currently stopped working. Tried on Android and iOS. Clear cache/data and so on doesn't resolve the problem. Attached screenshot: 
![dualnback](https://github.com/user-attachments/assets/12de8c7f-d852-4cc2-9fb8-cf5018fa09ff)

**Comment by jperryhouts** [comment]
I worked on this today and I think it should be fixed. I'll close this ticket, but please open it back up if you're still experiencing problems.

**Comment by tehniksit** [comment]
Yes, it works now.
